"""modify table Data, add att mean, min, max and std

Revision ID: 60dc9aa821c8
Revises: c41bd0f8f22c
Create Date: 2024-07-19 19:45:53.290919

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60dc9aa821c8"
down_revision: Union[str, None] = "c41bd0f8f22c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data", sa.Column("mean", sa.Float(), nullable=False))
    op.add_column("data", sa.Column("min", sa.Float(), nullable=False))
    op.add_column("data", sa.Column("max", sa.Float(), nullable=False))
    op.add_column("data", sa.Column("std", sa.Float(), nullable=False))
    op.drop_column("data", "value")
    op.create_index(op.f("ix_signal_name"), "signal", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_name"), table_name="signal")
    op.add_column(
        "data",
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("data", "std")
    op.drop_column("data", "max")
    op.drop_column("data", "min")
    op.drop_column("data", "mean")
    # ### end Alembic commands ###
