"""add index in timestamp

Revision ID: 0bbb72c69ab6
Revises: 84b53e673e8d
Create Date: 2024-07-18 21:59:57.302459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbb72c69ab6'
down_revision: Union[str, None] = '84b53e673e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_timestamp'), 'data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_timestamp'), table_name='data')
    # ### end Alembic commands ###
